name: YN
description: A sample Chrome packaged application
dependencies:
  browser: any
  chrome: any
  polymer: '>=0.9.1-dev <0.10.0'
dev_dependencies:
  grinder: any
  intl: any
transformers:
- polymer:
    entry_points: web/index.html
    csp: 'true'